import {
  ApiError,
  GenerateContentResponse,
  GoogleGenAI,
  type GenerateContentParameters,
} from "@google/genai";

import { serverEnv } from "@/lib/server-env";
import type { InlineImage } from "@/lib/services/image-generation/types";

export const geminiClient = new GoogleGenAI({
  apiKey: serverEnv.GEMINI_API_KEY,
});

export async function generateImageWithGemini({
  prompt,
  images,
}: {
  prompt: string;
  images: InlineImage[];
}): Promise<Buffer> {
  const payload: GenerateContentParameters = {
    model: "gemini-3-pro-image-preview",
    config: { imageConfig: { aspectRatio: "1:1", imageSize: "2K" } },
    contents: [
      { text: prompt },
      ...images.map((image) => ({
        inlineData: {
          mimeType: image.mediaType,
          data: image.imageBase64,
        },
      })),
    ],
  };

  let response: GenerateContentResponse | null = null;
  try {
    response = await geminiClient.models.generateContent(payload);
  } catch (error) {
    if (error instanceof ApiError && error.status >= 500 && error.status < 600) {
      response = await geminiClient.models.generateContent(payload);
    } else {
      throw error;
    }
  }

  const firstImage = response?.candidates?.[0]?.content?.parts
    ?.filter((part) => part.inlineData?.data)
    .map((part) => part.inlineData?.data)[0];

  if (!firstImage) {
    throw new Error("No image generated by Gemini");
  }

  return Buffer.from(firstImage, "base64");
}
